# Generated by Django 5.1.3 on 2024-11-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('role', models.CharField(max_length=300)),
                ('nationality', models.CharField(max_length=200)),
                ('baseprice', models.IntegerField()),
            ],
        ),
    ]
